dapiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-deployment
  labels:
    app: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: ghostrider412/cicd-app:d4ea8dafb508ef12fea36025b3ae2659e4a70352
        ports:
        - containerPort: 3000