dapiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-deployment
  labels:
    app: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: ghostrider412/cicd-app:0c6d5cdad1bd57693fa7ee00faaebc52ec8caf20
        ports:
        - containerPort: 3000